const assert = require('node:assert/strict');
const fs = require('node:fs');
const state = require('../../static/js/cloud-state.js');
const durable = require('../../static/js/durable-work.js');
const s = state.createState('alice');
s.pending = {text:'private'};
const ticket = state.beginRequest(s);
assert(Object.isFrozen(ticket));
state.changeContext(s,'bob');
assert.equal(state.acceptResponse(s,ticket),false);
assert.equal(s.pending,null);
const fresh=state.beginRequest(s);
assert(state.acceptResponse(s,fresh));
state.suspend(s);
assert(!state.acceptResponse(s,fresh));
assert.equal(s.pending,null);
state.resume(s,'bob');
assert(!state.acceptResponse(s,fresh));
assert(state.acceptResponse(s,state.beginRequest(s)));
const pending=durable.newSubmission('conversation',1,'text','stable-key');
assert.deepEqual(durable.retrySubmission(pending),pending);
const app=fs.readFileSync(require.resolve('../../static/js/cloud-app.js'),'utf8');
for (const unsafe of ['innerHTML','localStorage','sessionStorage','serviceWorker.register','eval(']) assert(!app.includes(unsafe),unsafe);
for (const required of ['textContent','X-CSRF-Token','X-Athena-Context','visibilitychange','pageshow','pagehide','BroadcastChannel','AbortController']) assert(app.includes(required),required);
console.log('PASS account state: stale tickets, context changes, suspension, stable retries and safe rendering primitives');
