#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill. Walks through Meta's WhatsApp Cloud API setup
# for this app and fills the META_WA_* variables in .env. Re-runnable: it
# offers every value already in .env as the default.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

banner "WhatsApp (Meta Cloud API) setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Meta app with the WhatsApp product"
say "Everything lives in one Meta app. Create it once; the rest of the wizard reads from it."
open_url "https://developers.facebook.com/apps/"
step "Click 'Create app'. Use case: 'Other' → app type 'Business'. Name it (e.g. Action Inbox)."
step "Attach it to a Business portfolio (create one if asked — this is your future verified business)."
step "On the app dashboard, find the WhatsApp product and click 'Set up'."
note "This gives you a free test number that can message up to 5 allowlisted phones."
pause "Press Enter once the app exists and WhatsApp is added."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "App secret"
say "Meta signs every webhook delivery with this. The app checks the signature before reading a message."
open_url "https://developers.facebook.com/apps/"
step "Open your app → left sidebar 'App settings' → 'Basic'."
step "On the 'App secret' row click 'Show' (it may ask for your password), then copy it."
ask_secret META_WA_APP_SECRET "Paste the app secret:"
write_env META_WA_APP_SECRET "$META_WA_APP_SECRET"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Sender: phone number ID, number, access token"
say "All three are on the API Setup page of the WhatsApp product."
open_url "https://developers.facebook.com/apps/"
step "Open your app → left sidebar 'WhatsApp' → 'API Setup'."
step "Under 'From', copy the 'Phone number ID' (a long number, not the phone number)."
ask META_WA_PHONE_NUMBER_ID "Paste the phone number ID:"
step "Next to it is the sender's phone number itself (the test number looks like +1 555 …). Copy it."
ask META_WA_PHONE_NUMBER "Paste the sender's phone number (with country code):"
step "At the top, 'Temporary access token' → 'Generate' (if needed) → copy it."
note "It expires after 24 hours. Fine for trying it; the last stage makes a permanent one."
ask_secret META_WA_ACCESS_TOKEN "Paste the access token:"
# A paste into a hidden prompt sometimes lands two or three times over. Every
# Meta token starts with EAA, so a second EAA means a repeat: keep the first copy.
if [[ "$META_WA_ACCESS_TOKEN" == EAA*EAA* ]]; then
  META_WA_ACCESS_TOKEN="EAA${META_WA_ACCESS_TOKEN#EAA}"
  META_WA_ACCESS_TOKEN="${META_WA_ACCESS_TOKEN%%EAA*}"
  warn "the token was pasted more than once; kept the first copy (${#META_WA_ACCESS_TOKEN} chars)"
fi
step "Below the token, copy the 'WhatsApp Business Account ID' as well."
ask META_WA_WABA_ID "Paste the WhatsApp Business Account ID:"
write_env META_WA_WABA_ID "$META_WA_WABA_ID"
write_env META_WA_PHONE_NUMBER_ID "$META_WA_PHONE_NUMBER_ID"
write_env META_WA_PHONE_NUMBER "$META_WA_PHONE_NUMBER"
write_env META_WA_ACCESS_TOKEN "$META_WA_ACCESS_TOKEN"
if confirm "Is this the free Meta test number (not a number you own)?"; then
  write_env META_WA_TEST_NUMBER 1
  note "Settings will tell users their number must be on the test number's recipient list."
else
  write_env META_WA_TEST_NUMBER 0
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Allowlist your own phone (test number only)"
if [[ "$(_existing META_WA_TEST_NUMBER || true)" == "1" ]]; then
  say "The test number only talks to phones on its recipient list — up to 5."
  step "Still on 'API Setup': under 'To', open the dropdown → 'Manage phone number list'."
  step "'Add phone number' → enter your WhatsApp number → enter the code WhatsApp sends you."
  note "Repeat for anyone else who should try it. A real number of your own has no such list."
  pause "Press Enter once your phone is on the list."
else
  say "You are on a number you own, so there is no recipient list to manage."
  pause "Press Enter to continue."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify token"
say "A string you make up. Meta echoes it back when you register the webhook, proving the URL is yours."
existing_verify=$(_existing META_WA_VERIFY_TOKEN || true)
if [[ -n "$existing_verify" ]]; then
  META_WA_VERIFY_TOKEN="$existing_verify"
  note "Keeping the token already in $ENV_FILE."
else
  if command -v openssl >/dev/null 2>&1; then
    META_WA_VERIFY_TOKEN=$(openssl rand -hex 16)
  else
    META_WA_VERIFY_TOKEN=$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')
  fi
  note "Generated one for you."
fi
write_env META_WA_VERIFY_TOKEN "$META_WA_VERIFY_TOKEN"
say "Verify token: ${BOLD}${META_WA_VERIFY_TOKEN}${RESET}  (you paste this into Meta in stage 8)"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "A public HTTPS URL for the webhook"
say "Meta must reach the app over the internet. Locally that means a tunnel."
step "In another terminal, with the web app about to run on port 5001:"
say "    ngrok http 5001"
note "Deploying instead? Use the deployment's public URL and skip the tunnel."
ask PUBLIC_URL "Paste the public https URL (e.g. https://abcd.ngrok-free.app):"
PUBLIC_URL="${PUBLIC_URL%/}"
if [[ "$PUBLIC_URL" != https://* ]]; then
  warn "Meta requires https. Double-check the URL."
fi
say "The app uses BASE_URL for the link it sends to unlinked numbers ('open .../settings')."
if confirm "Set BASE_URL=$PUBLIC_URL in $ENV_FILE?"; then
  write_env BASE_URL "$PUBLIC_URL"
  note "Sign-in still works from localhost: OAuth redirect URIs are computed per request."
else
  note "Leaving BASE_URL alone; the settings link in WhatsApp replies will point at its current value."
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Start the app and check the handshake"
say "The app reads $ENV_FILE at start, so it has to be (re)started now."
step "In another terminal:"
say "    source venv/bin/activate && flask --app app run --debug --port 5001"
pause "Press Enter once it is running."
say "Checking the handshake locally…"
challenge="wizard-$RANDOM"
got=$(curl -s --max-time 5 \
  "http://localhost:5001/whatsapp/webhook?hub.mode=subscribe&hub.verify_token=${META_WA_VERIFY_TOKEN}&hub.challenge=${challenge}" || true)
if [[ "$got" == "$challenge" ]]; then
  printf '  %s✓ handshake OK%s — the app answered with the challenge\n' "$GREEN" "$RESET"
else
  warn "handshake failed (got: '${got:-nothing}'). Is the app running with the new .env? Fix it before stage 8."
  pause
fi
if [[ -n "${PUBLIC_URL:-}" ]]; then
  got=$(curl -s --max-time 10 \
    "${PUBLIC_URL}/whatsapp/webhook?hub.mode=subscribe&hub.verify_token=${META_WA_VERIFY_TOKEN}&hub.challenge=${challenge}" || true)
  if [[ "$got" == "$challenge" ]]; then
    printf '  %s✓ reachable%s through %s\n' "$GREEN" "$RESET" "$PUBLIC_URL"
  else
    warn "the public URL did not answer the handshake (got: '${got:-nothing}'). Check the tunnel."
    pause
  fi
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Register the webhook with Meta"
open_url "https://developers.facebook.com/apps/"
step "Open your app → 'WhatsApp' → 'Configuration'."
step "Under 'Webhook' click 'Edit':"
say "    Callback URL:  ${BOLD}${PUBLIC_URL:-<your public url>}/whatsapp/webhook${RESET}"
say "    Verify token:  ${BOLD}${META_WA_VERIFY_TOKEN}${RESET}"
step "Click 'Verify and save'. Meta calls the URL; the app answers with the challenge."
step "Then under 'Webhook fields' click 'Manage' and subscribe to ${BOLD}messages${RESET}."
note "Only 'messages' is needed; the app ignores everything else."
pause "Press Enter once the webhook shows as verified and 'messages' is subscribed."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Subscribe the app to the Business Account"
say "Registering the webhook is not enough: the Business Account must also list your app."
say "Out of the box it lists only Meta's own dashboard app, so nothing reaches your webhook."
say "Subscribing now…"
subscribed=$(curl -s --max-time 15 -X POST \
  "https://graph.facebook.com/v23.0/${META_WA_WABA_ID}/subscribed_apps" \
  -H "Authorization: Bearer ${META_WA_ACCESS_TOKEN}" || true)
if [[ "$subscribed" == *'"success":true'* ]]; then
  printf '  %s✓ subscribed%s — the Business Account now delivers messages to your app\n' "$GREEN" "$RESET"
else
  warn "Meta answered: ${subscribed:-nothing}"
  warn "Check the token and the Business Account ID, then re-run this stage."
  pause
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Try it from your phone"
say "From the phone you allowlisted, send any message to ${BOLD}${META_WA_PHONE_NUMBER}${RESET} on WhatsApp."
say "Expected reply within a few seconds:"
say "    \"This number isn't linked to an account yet. Open …/settings …\""
note "No reply? Check the flask terminal for a signature or token error, and the ngrok inspector at http://127.0.0.1:4040."
pause "Press Enter once the reply arrived."
say "Now link the number: open Settings → WhatsApp card → enter your number → 'Get code',"
say "then send the code from your phone. The card flips to 'Linked' by itself."
open_url "${BASE_URL:-http://localhost:5001}/settings"
pause "Press Enter once it says Linked. Then just message the agent."

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Permanent access token (optional now, needed within 24h)"
say "The temporary token from stage 3 dies after 24 hours. A System User token does not."
if confirm "Create the permanent token now?"; then
  open_url "https://business.facebook.com/settings/system-users"
  step "Pick your Business portfolio (top-left) if asked."
  step "'Add' → name it (e.g. action-inbox), role 'Admin' → create."
  step "'Add assets' → 'Apps' → select your app → enable 'Manage app' → save."
  step "'Generate new token' → select your app → expiry 'Never' →"
  say "    permissions: ${BOLD}whatsapp_business_messaging${RESET} and ${BOLD}whatsapp_business_management${RESET}"
  step "Generate, copy the token (Meta shows it once)."
  ask_secret META_WA_ACCESS_TOKEN "Paste the permanent token:"
  write_env META_WA_ACCESS_TOKEN "$META_WA_ACCESS_TOKEN"
  note "Restart the app so it picks the new token up."
else
  SKIPPED+=("Permanent access token: the temporary one stops working 24h after it was generated (re-run this wizard, stage 11)")
fi

finish
say "Later, to serve anyone from a number you own: WhatsApp → API Setup → 'Add phone number',"
say "then Business settings → Security Centre → 'Start verification'. No code changes needed."
printf '\n'
