"""Executor selection for per-todo resolution.

`app.py` talks to whatever executor is configured through this one function, so
swapping Hermes for another CLI, a hosted API, or a home-grown loop is a change
here and nowhere else.

The contract every executor implements:

    resolve(todo, thread, user_message, user_id, state,
            cancel=None, progress=None, from_suggestion=False) -> (thread, state)

`thread` is the display log: a list of {role, content} bubbles, which is also a
valid Agents-SDK input list, so the two executors can read each other's threads.

`state` is an opaque per-executor string persisted in `todos.executor_state`.
Hermes keeps its session id there; the Agents-SDK resolver has no out-of-band
state (the thread *is* its state) and returns None. Nothing outside the executor
interprets it.

`cancel` is a `agent.runs.CancelToken` when the caller wants the run to be
stoppable, and None otherwise. Honouring it is best-effort and per-executor:
Hermes attaches its subprocess to the token so a stop kills it outright, while
the in-process Agents-SDK loop has nothing to interrupt and ignores it.

`progress` is an optional callback taking one `{tool, detail}` event, so the UI
can show what the agent is doing before it is finished doing it. Best-effort and
per-executor in the same way: Hermes tails its own session store to produce
events, the Agents-SDK loop reports nothing. Callers must treat "no events" as
normal, never as a stalled run.

`from_suggestion` says the message was produced by clicking one of the inferred
options rather than typed. It matters because the user consented to a four-word
label, not to the sentence behind it: an instruction generated by a model can
assert things about them they never said, and an executor that treats it as
their own words will act on those assertions instead of asking. Executors that
build a prompt should frame such a turn as a proposed route, not a statement.

Selection is per user. Each user picks an executor in Settings and the choice
is stored in `user_state`; `TODO_EXECUTOR` is only the default for users who
have not chosen. `hermes` needs the CLI on the host, so the deployed container —
which has no such binary — wants `agents_sdk` as its default, and `readiness`
is what keeps Settings from offering an executor that cannot run here.
"""

import importlib.util
import os
import shutil

DEFAULT_EXECUTOR = "hermes"

# Every executor there is, in the order Settings lists them. Adding one means an
# entry here, a branch in `_load`, and a readiness probe in `readiness`.
EXECUTORS = (
    {
        "name": "hermes",
        "label": "Hermes Agent",
        "description": "Browser, terminal and desktop tools. The most capable option.",
        "recommended": True,
    },
    {
        "name": "agents_sdk",
        "label": "Built-in OpenAI agent",
        "description": "Web search and Gmail only. Works without Hermes installed.",
        "recommended": False,
    },
)
EXECUTOR_NAMES = tuple(e["name"] for e in EXECUTORS)


class ExecutorError(RuntimeError):
    """An executor failed to produce a reply. Message is safe to show the user.

    `state` is the executor state the turn was running under, when the executor
    knows it — a first turn opens its session before anything can go wrong, and
    a stop halfway through should not forget that session, or the next turn's
    agent would have no memory of what it had already done. `None` means the
    caller keeps whatever state it had.
    """

    state: str | None = None


class ExecutorCancelled(ExecutorError):
    """The user stopped the run. A subclass, so plain error handlers still catch it.

    Whatever the agent had already done before the stop — mail sent, a form
    submitted — stands; only the run itself was interrupted.
    """


def _load(name: str):
    # Imported lazily so choosing one executor never pays for the other's
    # dependencies — notably, `hermes` should not drag in the Agents SDK.
    if name == "hermes":
        from agent.hermes_runner import resolve
    elif name == "agents_sdk":
        from agent.sdk_executor import resolve
    else:
        raise ExecutorError(
            f"Unknown executor {name!r}. Expected one of {', '.join(EXECUTOR_NAMES)}."
        )
    return resolve


def default_executor() -> str:
    """The server-wide default: TODO_EXECUTOR, else `hermes`."""
    return os.environ.get("TODO_EXECUTOR", DEFAULT_EXECUTOR).strip().lower()


def current_executor(choice: str | None = None) -> str:
    """The executor a turn runs on: the user's stored choice when it names a
    known executor, else the server default."""
    choice = (choice or "").strip().lower()
    return choice if choice in EXECUTOR_NAMES else default_executor()


def readiness(name: str) -> tuple[bool, str | None]:
    """Whether `name` can run a turn on this host, and if not, why.

    Cheap probes only — a binary on PATH, an importable package, a key in the
    environment — so Settings can ask on every open. A green light here means
    the next message will start a turn, not that the turn will succeed.
    """
    if name == "hermes":
        binary = os.environ.get("HERMES_BIN", "hermes")
        if shutil.which(binary) or os.path.isfile(binary):
            return True, None
        return False, (
            f"Hermes CLI not found (looked for {binary!r}). Install it, or set "
            "HERMES_BIN to where it lives."
        )
    if name == "agents_sdk":
        if importlib.util.find_spec("agents") is None:
            return False, "The openai-agents package is not installed."
        if not os.environ.get("OPENAI_API_KEY", "").strip():
            return False, "OPENAI_API_KEY is not set."
        return True, None
    return False, f"Unknown executor {name!r}."


def describe_executors(choice: str | None = None) -> dict:
    """What Settings shows: every executor, whether it is ready, and which one
    this user's turns run on."""
    options = []
    for entry in EXECUTORS:
        ready, reason = readiness(entry["name"])
        options.append({**entry, "ready": ready, "reason": reason})
    return {
        "selected": current_executor(choice),
        "default": default_executor(),
        "options": options,
    }


def resolve(
    todo: dict,
    thread: list,
    user_message: str,
    user_id: str,
    state: str | None,
    cancel=None,
    progress=None,
    from_suggestion: bool = False,
    executor: str | None = None,
) -> tuple[list, str | None]:
    """Run one turn on `executor` — the user's choice, resolved by the caller —
    or on the server default when none is given."""
    return _load(current_executor(executor))(
        todo, thread, user_message, user_id, state,
        cancel=cancel, progress=progress, from_suggestion=from_suggestion,
    )
